# Generated by Django 3.2.13 on 2023-05-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_userwebsite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='color_scheme',
            field=models.CharField(default='light', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='site',
            name='industry',
            field=models.CharField(default='Other', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
