# Generated by Django 3.2.13 on 2023-05-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20230515_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='template',
        ),
        migrations.AddField(
            model_name='site',
            name='template_name',
            field=models.CharField(default='walnut', max_length=255),
        ),
    ]
